import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/navbar";
import Footer from "@/Components/Footer/footer";
import Banner from "@/Components/Banner/Banner";
import favicon from './favicon.ico';
import ScrollToTopButton from "./_components/ScrollToTopButton/ScrollToTopButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "crown excel",
  description: "Generated by create next app",
  

};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      style={{backgroundColor:'white'}}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children }
        <Footer/>
        <ScrollToTopButton/>
      </body>
    </html>
  );
}
